insert into email (id, address, type, user_id)
values
(1,'jean.dupont@personal.com', 'PERSONAL', 1),
(2,'jean.dupont@professional.com', 'PROFESSIONAL', 1),
(3,'marie.martin@personal.com', 'PERSONAL', 2),
(4,'marie.martin@professional.com', 'PROFESSIONAL', 2),
(5,'pierre.durand@personal.com', 'PERSONAL', 3),
(6,'pierre.durand@professional.com', 'PROFESSIONAL', 3),
(7,'sophie.leclerc@personal.com', 'PERSONAL', 4),
(8,'sophie.leclerc@@professional.com', 'PROFESSIONAL', 4),
(9,'luc.lefevre@personal.com', 'PERSONAL', 5),
(10,'luc.lefevre@professional.com', 'PROFESSIONAL', 5),
(11,'isabelle.dupuis@personal.com', 'PERSONAL', 6),
(12,'isabelle.dupuis@professional.com', 'PROFESSIONAL', 6),
(13,'thomas.robert@personal.com', 'PERSONAL', 7),
(14,'thomas.robert@professional.com', 'PROFESSIONAL', 7),
(15,'elodie.girard@personal.com', 'PERSONAL', 8),
(16,'elodie.girard@professional.com', 'PROFESSIONAL', 8),
(17,'antoine.petit@personal.com', 'PERSONAL', 9),
(18,'antoine.petit@professional.com', 'PROFESSIONAL', 9),
(19,'julie.dubois@personal.com', 'PERSONAL', 10),
(20,'julie.dubois@professional.com', 'PROFESSIONAL', 10)